### ISSUE TITLE
In Array string with patterns some elements are empty

### ISSUE THREAD

**Issue by Filiponesco** [Filiponesco/Skradzione_wzory#2]
I get this error: System.IndexOutOfRangeException: „Indeks wykraczał poza granice tablicy.” in Algorytm.cs. I think it is because some elements in array string with patterns are empty. @Matikones Look at this screenshot.
![image](https://user-images.githubusercontent.com/44809428/71648076-de88a080-2cff-11ea-8635-a78fa9f28f46.png)
![image](https://user-images.githubusercontent.com/44809428/71648080-eb0cf900-2cff-11ea-98f8-a4e6949aa057.png)

**Comment by Matikones** [comment]
Błędem okazało się złe wczytywanie wzorów. Na kilka możliwości wczytywań dwie działały nieprawidłowo. Możliwości które działały złe to wzory umieszczane między "\(", a "\)" oraz "\[" i "\]". Problemem okazało się złe zamykanie. To jest program widział kiedy otworzyć wczytywanie jednak po pierwszym znaku \ zamykał. Stąd, gdy w pliku latexa wzór zaczynał się od znaku "\" program automatycznie zamykał wczytywanie wzoru przez co zostawał on pusty. Do naprawy wystarczyło dodać zmienną bool, która zmienia wartość na true, gdy po znaku "\" następuję znak "]" lub ")". Tylko wtedy pozwala programowi opuścić wczytywanie wzorów
